bookmarks/urls.py
# from django.conf.urls import url
# from bookmarks import views
# # urlpatterns = [
# #   path('', views.index, name='index'),
# # ]
# app_name = 'bookmarks'

# urlpatterns = [
#     url(r'^$', views.bookmark_list, name='bookmark_list'),
#     url(r'^new$', views.bookmark_create, name='bookmark_new'),
#     url(r'^edit/(?P<pk>\d+)$', views.bookmark_update, name='bookmark_edit'),
#     url(r'^delete/(?P<pk>\d+)$', views.bookmark_delete, name='bookmark_delete'),
# ]

from django.urls import include, re_path
from bookmarks import views
# urlpatterns = [
#   path('', views.index, name='index'),
# ]
app_name = 'bookmarks'

urlpatterns = [
    re_path(r'^$', views.bookmark_list, name='bookmark_list'),
    re_path(r'^new$', views.bookmark_create, name='bookmark_new'),
    re_path(r'^edit/(?P<pk>\d+)$', views.bookmark_update, name='bookmark_edit'),
    re_path(r'^delete/(?P<pk>\d+)$', views.bookmark_delete, name='bookmark_delete'),
]

djorg/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from graphene_django.views import GraphQLView
# from rest_framework import routers
# from notes.api import NoteViewSet

app_name = 'bookmarks'
# url(r'^api-auth/', include('rest_framework.urls'))
# router = routers.DefaultRouter()
# router.register(r'notes', NoteViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('notes.urls')),
    # path('api/', include(router.urls)),
    path('bookmarks/', include('bookmarks.urls', namespace='bookmarks')),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('', TemplateView.as_view(template_name='djorg_base.html')),
    path('', include('bookmarks.urls', namespace='bookmarks')),       
]

notes/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.ListNote.as_view()),
  path('<int:pk>/', views.DetailNote.as_view()),
]

bookmarks/models.py
from django.db import models
from uuid import uuid4
from django.urls import reverse

# Create your models here.
# TODO ADD bookmarked on column (see Question model from django tutorial)
class Bookmark(models.Model):
  """ Bookmarks model """
  created_at = models.DateTimeField(auto_now_add=True)
  description = models.TextField(blank=True)
  last_modified = models.DateTimeField(auto_now=True)
  name = models.CharField(max_length=200)
  tag = models.TextField(blank=True)
  url = models.URLField('URL', unique=True)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('bookmark_edit', kwargs={'pk' : self.pk})
    

notes/models.py
# from uuid import uuid4
from django.contrib.auth.models import User
from django.db import models

class Note(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

bookmarks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from .models import Bookmark


class BookmarkForm(forms.ModelForm):
  class Meta:
    model = Bookmark
    fields = ['name', 'url', 'tag', 'description']

def bookmark_list(request, template_name='bookmarks/bookmark_list.html'):
  bookmarks = Bookmark.objects.all()
  data = {}
  data['object_list'] = bookmarks
  return render(request, template_name, data)

def bookmark_create(request, template_name='bookmarks/bookmark_form.html'):
  # or None ??? 
  form = BookmarkForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('bookmarks:bookmark_list')
  return render(request, template_name, {'form': form})

def bookmark_update(request, pk, template_name='bookmarks/bookmark_edit.html'):
  bookmark = get_object_or_404(Bookmark, pk=pk)
  form = BookmarkForm(request.POST or None, instance = bookmark)
  if form.is_valid():
    form.save()
    return redirect('bookmarks:bookmark_list')
  return render(request, template_name, {'form':form})

def bookmark_delete(request, pk, template_name='bookmarks/bookmark_confirm_delete.html'):
  bookmark = get_object_or_404(Bookmark, pk=pk)
  if request.method == 'POST':
    bookmark.delete()
    return redirect('bookmarks:bookmark_list')
  return render(request, template_name, {'object': bookmark})
















# class bookmarks(View):
#   template_name = 'bookmarks/index.html'

#   def get(self, request):
#     # context = {}
#     # context['bookmarks'] = Bookmark.objects.all()
#     # context['personal_bookmarks'] = PersonalBookmark.objects.all()
#     # context['form'] = BookmarkForm()
#     bookmark_list = []
#     form_user = BookmarkForm()
#     bookmarks = Bookmark.objects.all()

#     for bookmark in bookmarks:
#       bookmark_list.append({'Name': bookmark.name, 'Url': bookmark.url})

#     return render(request, self.template_name, {
#       'bookmark_list': bookmark_list,
#       'form_user': form_user
#     })

#   def post(self, request):
#     form_user = BookmarkForm(request.POST)
#     if form_user.is_valid():
#         form_user.save()
#         return HttpResponseRedirect('/bookmarks')


# def index(request):
#   # TODO: business logic, get data, etc...
#   context = {}
#   context['bookmarks'] = Bookmark.objects.all()
#   context['form'] = BookmarkForm()
#   return render(request, 'bookmarks/index.html', context)

notes/views.py
from rest_framework import generics

from . import models
from . import serializers

class ListNote(generics.ListCreateAPIView):
  queryset = models.Note.objects.all()
  serializer_class = serializers.NoteSerializer

class DetailNote(generics.RetrieveUpdateDestroyAPIView):
  queryset = models.Note.objects.all()
  serializer_class = serializers.NoteSerializer

bookmarks/templates/bookmarks/bookmark_confirm_delete.html
{% extends "djorg_base.html" %}
{% block content %}

<h1>Delete bookmark</h1>

<p>Are you sure you want to delete the bookmark for: {{ object.name }}?</p>

<form method="post">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

bookmarks/templates/bookmarks/bookmark_edit.html
{% extends "djorg_base.html" %}
{% block content %}
<h2>Edit Bookmark</h2>
<form method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <button type="submit">Save Changes</button>
</form>
{% endblock %}

bookmarks/templates/bookmarks/bookmark_form.html
{% extends "djorg_base.html" %}
{% block content %}
<h2>Add a New Bookmark</h2>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <button type="submit">Add Bookmark</button>
</form>
{% endblock %}

bookmarks/templates/bookmarks/bookmark_list.html
{% extends "djorg_base.html" %}
{% block content %} 

{% if object_list %}

<h1>Bookmark List</h1>
<ol>
  {% for bookmark in object_list %}
  <li>
    <a target="_blank" href="{{ bookmark.url }}">{{ bookmark.name }}</a>
    <ul>
      <li><a href="{% url 'bookmarks:bookmark_edit' bookmark.id %}">edit</a> </li>
      <li><a href="{% url 'bookmarks:bookmark_delete' bookmark.id %}">delete</a></li>
    </ul>
    <br>
  </li>
  {% endfor %}
</ol>
{% else %}
<p>No bookmarks found currently</p>
{% endif %}
<a href="{% url 'bookmarks:bookmark_new' %}">new</a>
{% endblock %}

bookmarks/templates/bookmarks/index.html
{% block content %}
{% if bookmark_list %}
 <h1>Bookmark List</h1>
 <h2>Public</h2>
<ol>
  {% for bookmark in bookmark_list %}
  <li>
    <a target="_blank" href="{{ bookmark.Url }}">{{ bookmark.Name }}</a>
  </li>
  {% endfor %}
</ol>
{% else %}
<p>No bookmarks found currently</p>
{% endif %}

{% if personal_bookmarks %}
<h2>Personal</h2>
<ol>
  {% for bookmark in personal_bookmarks %}
  <li>
    <a href="{{ bookmark.url }}">{{ bookmark.name }}</a>
  </li>
  {% endfor %}
</ol>
{% else %}
<p>No personal bookmarks available - you should add some!</p>
{% endif %}

{% include "bookmarks/bookmark_form.html" %}
{% endblock %}
<!-- <h2>Add a New Bookmark</h2>
<form method="POST" action="/bookmarks/">
  {% csrf_token %}
  <table>
    {{ form_user }}
  </table>
  <button type="submit">Add Bookmark</button>
</form> -->

bookmarks/templates/djorg_base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}Djorg{% endblock %}</title>
  {# Load Bootstrap CSS and JavaScript #} {% bootstrap_css %} {% bootstrap_javascript jquery='full' %}
</head>

<body>
  <div id="menu">
    {% block menu %}
    <ul>
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <a href="/bookmarks">Bookmarks</a>
      </li>
    </ul>
    {% endblock %}
  </div>

  <div id="content">
    {% block content %}
    <h1>Welcome to Djorg!</h1>
    {% endblock %}
  </div>
</body>

</html>